# EDA 및 전처리

## 라이브러리 불러오기

In [1]:
import pandas as pd
import numpy as np
import warnings
import joblib

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, confusion_matrix
from xgboost import XGBClassifier

warnings.filterwarnings('ignore')

## 데이터 불러오기

In [2]:
df = pd.read_csv('./data/loan_data.csv')
df.head()

,나이,성별,연소득,근속연수,주거형태,신용점수,기존대출건수,연간카드사용액,부채비율,대출신청액,대출목적,상환방식,대출기간,승인여부
0,42,여,4500,16,전세,613,2,3140,28.5,3000,자동차,원금균등,36,1
1,36,남,2400,4,월세,437,3,1260,54.2,2200,주택구입,원리금균등,36,0
2,43,남,4900,15,월세,623,2,3210,28.2,3800,자동차,원리금균등,48,1
3,51,여,2500,22,자가,608,1,1720,35.7,5600,전세자금,원리금균등,36,0
4,35,여,3900,3,월세,549,0,1630,49.5,7300,생활비,원리금균등,24,0

## EDA

In [ ]:
df.shape

(1500, 14)

In [ ]:
df.dtypes

나이           int64
성별          object
연소득          int64
근속연수         int64
주거형태        object
신용점수         int64
기존대출건수       int64
연간카드사용액      int64
부채비율       float64
대출신청액        int64
대출목적        object
상환방식        object
대출기간         int64
승인여부         int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   나이       1500 non-null   int64
 1   성별       1500 non-null   object
 2   연소득      1500 non-null   int64
 3   근속연수     1500 non-null   int64
 4   주거형태     1500 non-null   object
 5   신용점수     1500 non-null   int64
 6   기존대출건수   1500 non-null   int64
 7   연간카드사용액  1500 non-null   int64
 8   부채비율     1500 non-null   float64
 9   대출신청액    1500 non-null   int64
 10  대출목적     1500 non-null   object
 11  상환방식     1500 non-null   object
 12  대출기간     1500 non-null   int64
 13  승인여부     1500 non-null   int64
dtypes: float64(1), int64(9), object(4)
memory usage: 164.2+ KB

In [ ]:
df.isnull().sum()

나이         0
성별         0
연소득        0
근속연수       0
주거형태       0
신용점수       0
기존대출건수     0
연간카드사용액    0
부채비율       0
대출신청액      0
대출목적       0
상환방식       0
대출기간       0
승인여부       0
dtype: int64

In [ ]:
df.describe()  # 숫자형

,나이,연소득,근속연수,신용점수,기존대출건수,연간카드사용액,부채비율,대출신청액,대출기간,승인여부
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000
mean,38.078667,3884.866667,6.074667,568.626667,1.258000,1757.760000,37.353867,3418.533333,36.840000,0.608667
std,8.582633,1521.267175,5.136927,86.603931,1.136206,995.241538,15.070179,1825.101964,13.990886,0.488211
min,23.000000,1500.000000,0.000000,300.000000,0.000000,280.000000,3.000000,500.000000,12.000000,0.000000
25%,32.000000,2800.000000,2.000000,510.750000,0.000000,1000.000000,25.975000,2200.000000,24.000000,0.000000
50%,38.000000,3650.000000,5.000000,569.000000,1.000000,1590.000000,36.500000,3000.000000,36.000000,1.000000
75%,44.000000,4700.000000,9.000000,626.000000,2.000000,2260.000000,47.825000,4200.000000,48.000000,1.000000
max,65.000000,13900.000000,30.000000,900.000000,5.000000,6620.000000,83.900000,15000.000000,60.000000,1.000000

In [ ]:
df.describe(include='all') # 모든 컬럼

,나이,성별,연소득,근속연수,주거형태,신용점수,기존대출건수,연간카드사용액,부채비율,대출신청액,대출목적,상환방식,대출기간,승인여부
count,1500.000000,1500,1500.000000,1500.000000,1500,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500,1500,1500.000000,1500.000000
unique,NaN,2,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,7,3,NaN,NaN
top,NaN,남,NaN,NaN,전세,NaN,NaN,NaN,NaN,NaN,주택구입,원리금균등,NaN,NaN
freq,NaN,868,NaN,NaN,615,NaN,NaN,NaN,NaN,NaN,289,822,NaN,NaN
mean,38.078667,NaN,3884.866667,6.074667,NaN,568.626667,1.258000,1757.760000,37.353867,3418.533333,NaN,NaN,36.840000,0.608667
std,8.582633,NaN,1521.267175,5.136927,NaN,86.603931,1.136206,995.241538,15.070179,1825.101964,NaN,NaN,13.990886,0.488211
min,23.000000,NaN,1500.000000,0.000000,NaN,300.000000,0.000000,280.000000,3.000000,500.000000,NaN,NaN,12.000000,0.000000
25%,32.000000,NaN,2800.000000,2.000000,NaN,510.750000,0.000000,1000.000000,25.975000,2200.000000,NaN,NaN,24.000000,0.000000
50%,38.000000,NaN,3650.000000,5.000000,NaN,569.000000,1.000000,1590.000000,36.500000,3000.000000,NaN,NaN,36.000000,1.000000
75%,44.000000,NaN,4700.000000,9.000000,NaN,626.000000,2.000000,2260.000000,47.825000,4200.000000,NaN,NaN,48.000000,1.000000
max,65.000000,NaN,13900.000000,30.000000,NaN,900.000000,5.000000,6620.000000,83.900000,15000.000000,NaN,NaN,60.000000,1.000000

In [ ]:
df.describe(include='O')  # 범주형

          성별  주거형태  대출목적   상환방식
count   1500  1500  1500   1500
unique     2     3     7      3
top        남    전세  주택구입  원리금균등
freq     868   615   289    822

In [ ]:
df['성별'].value_counts()

성별
남    868
여    632
Name: count, dtype: int64

In [ ]:
df['주거형태'].value_counts()

주거형태
전세    615
자가    469
월세    416
Name: count, dtype: int64

In [ ]:
df['대출목적'].value_counts()

대출목적
주택구입    289
생활비     265
전세자금    263
사업자금    219
자동차     215
교육비     144
의료비     105
Name: count, dtype: int64

In [ ]:
df['상환방식'].value_counts()

상환방식
원리금균등    822
원금균등     455
만기일시     223
Name: count, dtype: int64

## 레이블 인코딩

In [3]:
label_encoder = LabelEncoder()

df['성별'] = label_encoder.fit_transform(df['성별'])
df['성별']

0       1
1       0
2       0
3       1
4       1
       ..
1495    0
1496    0
1497    0
1498    0
1499    1
Name: 성별, Length: 1500, dtype: int64

In [4]:
df['주거형태'] = label_encoder.fit_transform(df['주거형태'])
df['주거형태']

0       2
1       0
2       0
3       1
4       0
       ..
1495    1
1496    1
1497    2
1498    1
1499    0
Name: 주거형태, Length: 1500, dtype: int64

In [5]:
df['대출목적'] = label_encoder.fit_transform(df['대출목적'])
df['대출목적']

0       4
1       6
2       4
3       5
4       2
       ..
1495    2
1496    1
1497    0
1498    6
1499    2
Name: 대출목적, Length: 1500, dtype: int64

In [6]:
df['상환방식'] = label_encoder.fit_transform(df['상환방식'])
df['상환방식']

0       1
1       2
2       2
3       2
4       2
       ..
1495    1
1496    1
1497    2
1498    2
1499    0
Name: 상환방식, Length: 1500, dtype: int64

In [7]:
df.head()

,나이,성별,연소득,근속연수,주거형태,신용점수,기존대출건수,연간카드사용액,부채비율,대출신청액,대출목적,상환방식,대출기간,승인여부
0,42,1,4500,16,2,613,2,3140,28.5,3000,4,1,36,1
1,36,0,2400,4,0,437,3,1260,54.2,2200,6,2,36,0
2,43,0,4900,15,0,623,2,3210,28.2,3800,4,2,48,1
3,51,1,2500,22,1,608,1,1720,35.7,5600,5,2,36,0
4,35,1,3900,3,0,549,0,1630,49.5,7300,2,2,24,0

## 학습 / 테스트 데이터 분리

### 입력(피처) --> X  --> 타겟을 제외한 나머지 모든 컬럼
### 정답(타겟) --> y  --> 승인 여부 (y/n)

In [8]:
X = df.drop('승인여부', axis=1) 
y = df['승인여부']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1200, 13), (300, 13), (1200,), (300,))

## 파이프라인 (스케일링 + 머신러닝 모델링)

In [11]:
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', XGBClassifier(
        n_estmators=100,
        max_depth=5,
        learning_rate=0.1,
        random_state=42,
        eval_metric='logloss'
    ))
])

In [12]:
pipeline

Pipeline(steps=[('scaler', StandardScaler()),
                ('model',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric='logloss',
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.1,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=5, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_estmators=100, n_jobs=None, ...))])

### 학습

In [13]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric='logloss',
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.1,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=5, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_estmators=100, n_jobs=None, ...))])

### 평가

In [14]:
y_pred = pipeline.predict(X_test)
y_pred

array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1])

## 평가지표 - 정확도

In [15]:
accuracy_score(y_test, y_pred)

0.8366666666666667

### 혼동행렬

In [16]:
confusion_matrix(y_test, y_pred)

array([[ 94,  29],
       [ 20, 157]])

### 피처 중요도 (Feature Importance)

In [17]:
pipeline.named_steps['model']

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_estmators=100,
              n_jobs=None, ...)

In [18]:
pipeline.named_steps['model'].feature_importances_

array([0.06888757, 0.02454716, 0.18136209, 0.12670676, 0.06932269,
       0.08949737, 0.05905815, 0.04399567, 0.04461752, 0.14481474,
       0.03289025, 0.08207877, 0.03222131], dtype=float32)

In [19]:
xgb_model = pipeline.named_steps['model']
feature_names = X.columns

In [22]:
pd.Series(xgb_model.feature_importances_, index=feature_names).sort_values(ascending=False)

연소득        0.181362
대출신청액      0.144815
근속연수       0.126707
신용점수       0.089497
상환방식       0.082079
주거형태       0.069323
나이         0.068888
기존대출건수     0.059058
부채비율       0.044618
연간카드사용액    0.043996
대출목적       0.032890
대출기간       0.032221
성별         0.024547
dtype: float32